### ISSUE TITLE
Clarification - Azure Locking 

### ISSUE THREAD

**Issue by vishnuvg1984** [htgc/fluent-plugin-azurestorage#11]
Hi , I like to discuss a thing. Incase if the target azure blob folder is locked, how the plugin will handle. Will it result in an error or anyway to handle this by generating another folder_1, incase if the folder exists. 
Azure suports locking mechanism and we like to lock a folder for a partcular time, so at that time , will the plugin creats a new folder name, bcz of not able to access the locked folder

**Comment by toddysm** [comment]
@vishnuvg1984 This is a quite an old question you posted but I started reviewing the filed issues and cleaning up the log hence we need to address this before closing. 
Question for you - I am not sure what you mean with locking Azure blob folder. In general Azure Storage has no concept of folders but just containers and blobs. Are you talking about obtaining a lease on the container?
To answer your question, because the library uses the standard Azure Storage SDK it behaves the same way the SDK behaves, which as far as I remember throws error if the container is locked.

**Comment by toddysm** [comment]
Closing this issue as answered.
